version: "1"

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: entrega_final
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: entregafinal/entrega_final
    environment:
      DB_HOST: database
    ports:
      - "9090:9090"
volumes:
  db-volume:
